### ISSUE TITLE
Folder & File Structure

### ISSUE THREAD

**Issue by dorakuflu** [Avdan-OS/Compositor#3]
I'm currently working on a system regarding the basics of the tiling mode. When I finish, should I include my code in main.rs? I took a look at other wayland wms like sway and wayfire and they seem to use different folders for the wm features and the compositor features.

**Comment by Sammy99jsp** [comment]
Definitely in different folder and module such as `windowing` or something...

**Comment by froxcey** [comment]
It's like web dev, putting everything in one file is not ideal. 

Since your question is answered, I will be closing this now.
