### ISSUE TITLE
[Bug] - Doesn't compile

### ISSUE THREAD

**Issue by Froxcey** [Avdan-OS/Compositor#65]
### Please make sure your system is up to date

- [X] Yes, my system is up to date

### Select your CPU architecture

AArch64

### Select your Linux distribution

Archlinux

### Please enter your RAM size

16G

### Please enter your GPU model

M1

### Please enter any additional hardware and software information

Bare-metal build:
Asahi linux, stable channel
M1, 2020, 16G

Container build:
Ubuntu 22.04.1 aarch64, 5.15.49-linuxkit kernel
Docker Container

Compiler:
Nightly 1.69.0

### Please explain what went wrong

Doesn't compile. 

### Provide us links that may help us fix this issue, if you have any

[Build.log](https://github.com/Avdan-OS/Compositor/files/10529004/build.log)

### Provide a screenshot of the problem, if you can

![vibe](https://user-images.githubusercontent.com/51555391/176177206-ec3f9dce-8780-4fe8-b6ac-5eeeac2038d4.gif)

### Additional information

^-^

### Please make sure this issue is not a duplicate of an existing issue.

- [X] Yes, I have searched for this issue on this repository and none were found

**Comment by MrSerge01** [comment]
> ### Additional information
> ^-^

lmao

**Comment by Froxcey** [comment]
Ok so... [Smithay updated](https://github.com/Smithay/smithay/commit/3cfdcd7840c28a12176e7d39f1e932abd3922f02) to use u64 instead of u32, but this repo still expects u32. I think that's why the code doesn't compile.
